
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: SocialMath

# Short bio or description (displayed in the header)
description: Mathematics for Describing Social Phenomena

# Default URL is just the title of the page without the path
permalink: /:title/

# Collections (see http://ben.balter.com/2015/02/20/jekyll-collections/)
collections:
  math-background:
    output: true
    permalink: /math_background/:path/
  love:
    output: true
    permalink: /love/:path/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
